language: python
python:
  - "2.7"
  - "3.5"

services:
 #- mysql
 - postgresql
env:
  - DJ=1.8 DB=sqlitefile
  - DJ=1.8 DB=postgres

before_script:
  - psql -c 'create database aristotle_test_db;' -U postgres
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2 --quiet; fi
  - "pip install coveralls"
  - "pip install -r requirements.txt"
  - "pip install ."
  - pip install -q Django==$DJ
  - "pip install django_tools"

# command to run tests
script:
  - coverage run --branch --source=aristotle_dse manage.py test aristotle_dse.tests
after_success:
  - coveralls

# Lets run on the new infrastructure
sudo: false

