# Lets run on the new infrastructure
sudo: false

language: python
python:
  - "3.5"
  - "2.7"

services:
  - postgresql
  - redis-server
  - elasticsearch

env:
  - DOCS=1
  - A11Y=1
  - DJANGO_VERSION='1.8'  DB=postgres ARISTOTLE_VERSION=1.6
  - DJANGO_VERSION='1.10' DB=postgres ARISTOTLE_VERSION=1.6
  - DJANGO_VERSION='1.10' DB=postgres ARISTOTLE_VERSION=develop

before_install:
  - pip install coveralls

install:
  - pip install tox

before_script:
# We only test elasticsearch, and a small setup time is recommended
  - sleep 10; 
# Make a posgres database
  - if [[ $DB == postgres ]]; then psql -c 'create database aristotle_test_db;' -U postgres; fi

# command to run tests
script:
# Start a few workers
#  - ./manage.py runworker --settings=aristotle_mdr.tests.settings.settings > worker1.log 2>&1 &
  - if [[ "$DB" != "" ]]; then tox -e dj$DJANGO_VERSION-test-db-$DB-search-whoosh-aristotle$ARISTOTLE_VERSION --skip-missing-interpreters  --workdir /tmp/tox; fi
# check documentation builds cleanly
  - if [[ $DOCS == 1 ]]; then tox -e pep8 -e docs --skip-missing-interpreters; fi
  - if [[ $A11Y != "" ]]; then tox -e ally --skip-missing-interpreters; fi
#  - cat worker1.log
after_success:
  - coveralls

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch

matrix:
  exclude:
    - python: "2.7"
      env: A11Y=1
    - python: "2.7"
      env: DOCS=1

  allow_failures:
    - env: DJANGO_VERSION='1.10' DB=postgres ARISTOTLE_VERSION=develop
